#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

BUILDER_TYPE="$1"; APP="$2"; IMAGE=$3; FILE_ROOT="$DOKKU_ROOT/$APP/DOKKU_FILES"
verify_app_name "$APP"

if [[ -d "$FILE_ROOT" ]] && [[ -n $(ls -p "$FILE_ROOT") ]]; then
  dokku_log_info1 "Copying files into image..."
  for path in $FILE_ROOT/*; do
    file=$(basename $path)
    dokku_log_verbose "- Copying $file"
    id=$("$DOCKER_BIN" container run -i -a stdin $IMAGE /bin/bash -c "cat > /app/$file" < "$path")
    test "$(docker wait $id)" -eq 0
    docker commit $id $IMAGE > /dev/null
    docker stop $id > /dev/null 2>&1 || true
    docker kill $id > /dev/null 2>&1 || true
  done
fi
